### ISSUE TITLE
PIndexImplType.Description should be validated

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#34]
I'm trying to integrate the CBGT REST endpoints into Sync Gateway, and getting the following crash:

```
2015/08/31 15:10:25 indexType: blackhole, t: &{Validate:<nil> New:0x4173340 Open:0x41735f0 Count:<nil> Query:<nil> Description:advanced/blackhole - a blackhole index ignores all data and is not queryable; used for testing StartSample:<nil> QuerySamples:<nil> QueryHelp: InitRouter:<nil> DiagHandlers:[] MetaExtra:<nil>}
2015/08/31 15:10:25 indexType: sync_gateway, t: &{Validate:<nil> New:0x40933e0 Open:0x4093500 Count:<nil> Query:<nil> Description:Sync Gateway Pindex StartSample:<nil> QuerySamples:<nil> QueryHelp: InitRouter:<nil> DiagHandlers:[] MetaExtra:<nil>}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/couchbaselabs/cbgt/rest.(*CreateIndexHandler).RESTOpts(0xc20815af50, 0xc2082716b0)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbaselabs/cbgt/rest/rest_create_index.go:44 +0x16c1
github.com/couchbaselabs/cbgt/rest.func·001(0x4869cf0, 0x16, 0x4807300, 0x3, 0x50ce1a8, 0xc20815af50, 0xc2082716b0)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbaselabs/cbgt/rest/rest.go:137 +0x99
github.com/couchbaselabs/cbgt/rest.InitRESTRouter(0xc20818cc30, 0x47ff420, 0x5, 0xc208031b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4af0af8, ...)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbaselabs/cbgt/rest/rest.go:161 +0x421
github.com/couchbaselabs/cbgt/rest.NewRESTRouter(0x47ff420, 0x5, 0xc208031b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4af0af8, 0x4af0b00, ...)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbaselabs/cbgt/rest/rest.go:120 +0x201
github.com/couchbase/sync_gateway/rest.CreateAdminHandler(0xc20802cbe0, 0x0, 0x0)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:220 +0x29e4
github.com/couchbase/sync_gateway/rest.RunServer(0xc208074b40)
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:611 +0x7f2
github.com/couchbase/sync_gateway/rest.ServerMain()
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:628 +0x34
main.main()
    /Users/tleyden/Development/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:33 +0x195
```

and it looks like the root problem is that I set the description to "Sync Gateway", but the expected description format is:

```
    // Description is used to populate docs, UI, etc, such as index
    // type drop-down control in the web admin UI.  Format of the
    // description string:
    //
    //    $categoryName/$indexType - short descriptive string
    //
    // The $categoryName is something like "advanced", or "general".
    Description string
```

I think that there should be some sort of validation when setting the Description field, or a graceful fallback in the code that tries to extract the description.   (or both)

**Comment by steveyen** [comment]
Hi Traun,
Sorry that you had to suffer on this one.

As I pull out the "wontfix" tag here, I'm going to apply the rather lame "there will only be 5 computers in the world" kind of rationale .. :-)

In that I'm guessing that the planetary-wide population of cbgt API users should be a rarified breed of folks, and I kinda suspect that we should able to all fit into a van ride together and all road trip to Tahoe together.  And, those van riders will have to suffer a little bit in the uncommon case when they on-board onto the van, rather than me introducing more (likely buggy!) code.
